config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :documents
  authenticated :user do
  	root "documents#index", as: "authenticated_root"
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
  }
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :documents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
	before_action :find_document, only: [:show,:edit,:update,:destroy]
	def index
		@documents = Document.where(user_id: current_user).all.order("created_at DESC")
	end
	def new	
		@document = current_user.documents.build
	end

	def show

	end


	def create
		@document = current_user.documents.build(document_params)
		if @document.save
			redirect_to  @document
		else
			render 'new'
		end
	end
	def edit
		
	end

	def update
		if @document.update(document_params)
			redirect_to @document
		else
			render 'edit'
		end
	end

	def destroy
		@document.destroy
		redirect_to documents_path
	end

	private

	def find_document
		@document = Document.find(params[:id])
	end

	def document_params
		params.require(:document).permit(:title,:content)
	end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/documents/_form.html.haml
= simple_form_for @document do |f|
	=f.input :title
	=f.input :content
	=f.button :submit, class: "button"

app/views/documents/edit.html.haml
.wrapper_with_padding	
	%h1 editando documento: #{ @document.title}
	= render 'form'
	= link_to "Cancelar", document_path

app/views/documents/index.html.haml
.wrapper_with_padding
	#documents.clearfix
		-unless @documents.blank?
			-@documents.each do |document|
				%a{href: (url_for [document])}
					.document
						%p.title    document.title
						%p.date= time_ago_in_words(document.created_at)
						%p.content= truncate(document.content, length:50)
		-else
			%h2 !Crea un documento¡
			%p !Crea documentos y organiza tu vida¡
			%button= link_to "Crear documento nuevo", new_document_path

app/views/documents/new.html.haml
.wrapper_with_padding	
	%h1 Nuevo Documento

	= render 'form'
	=link_to "Atras", documents_path

app/views/documents/show.html.haml
.wrapper_with_padding
	#document_show
		%h1.title= @document.title
		%p= simple_format(@document.content)
	.buttons	
		= link_to 'editar documento', edit_document_path(@document), class: "button" 
		= link_to 'Eliminar documento', document_path(@document), method: :delete, data: {confirm: "Estas de acuerdo en eliminar este documento: #{@document.title}"}, class: "button" 

= link_to 'Todos los documentos', documents_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Gestor de archivos | !El trabajo de tu vida¡
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header
      .header_inner
        =link_to "Gestor de archivos", root_path, id: "logo"
        %nav
          - if user_signed_in?
            = link_to "Crear Documento", new_document_path
            = link_to "Cerrar Sesión", destroy_user_session_path, method: :delete
          -else
            = link_to "Inciar Sesión", new_user_session_path
    %p.notice= notice
    %p.alert= alert
    = yield

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/welcome/index.html.haml
#banner
	.banner_content
		%h1 Gestor de Archivos
		%p El trabajo de tu vida, siempre organizado.
		%button= link_to "Registrarse", new_user_registration_path

#callouts
	.callouts_inner
		.wrapper
			.callout
				%h2 Organizar
				%p aslñdfkjasdlfsjdf
				%p asdlfkajsdflasdkfjasñldfkasjfalfaskjf
				

#bottom_cta
	.wrapper
	%h2 !Vamos¡
	%br
	%button=link_to "Unete ahora", new_user_registration_path 